# Generated by Django 4.2.26 on 2025-11-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="language_requirements",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="required_skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
