# Generated by Django 4.2.26 on 2026-01-14 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employers", "0002_alter_jobposting_language_requirements_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employerprofile",
            name="business_name",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="city",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="contact_person",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="phone_number",
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="region",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="verification_status",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="application_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("under_review", "Under Review"),
                    ("shortlisted", "Shortlisted"),
                    ("rejected", "Rejected"),
                    ("hired", "Hired"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="applied_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="city",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="education_required",
            field=models.CharField(
                db_index=True,
                help_text="Minimum education level required",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="experience_required",
            field=models.IntegerField(
                db_index=True, help_text="Minimum years of experience required"
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="location",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="region",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="religion_preference",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Preferred religion (if any)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="salary_max",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="salary_min",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("filled", "Filled"),
                    ("closed", "Closed"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="title",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="working_arrangement",
            field=models.CharField(
                choices=[
                    ("full_time", "Full-time"),
                    ("part_time", "Part-time"),
                    ("contract", "Contract"),
                    ("temporary", "Temporary"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
