# Generated by Django 4.2.26 on 2025-11-26 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("employers", "0002_alter_jobposting_language_requirements_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "job_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_threads",
                        to="employers.jobposting",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="message_threads", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("job_interest", "Job Interest"),
                            ("job_application", "Job Application"),
                            ("shortlist", "Shortlisted for Job"),
                            ("profile_approval", "Profile Approval"),
                            ("profile_rejection", "Profile Rejection"),
                            ("profile_update_required", "Profile Update Required"),
                            ("message_received", "New Message"),
                            ("job_status_change", "Job Status Change"),
                            ("system_alert", "System Alert"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_via_email", models.BooleanField(default=False)),
                ("sent_via_sms", models.BooleanField(default=False)),
                ("sent_via_push", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_4e3567_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "created_at"],
                        name="notificatio_notific_f2e0f7_idx",
                    ),
                    models.Index(
                        fields=["recipient", "created_at"],
                        name="notificatio_recipie_f39341_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sensitivity_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_for_sender", models.BooleanField(default=False)),
                ("deleted_for_recipient", models.BooleanField(default=False)),
                ("is_urgent", models.BooleanField(default=False)),
                (
                    "read_by",
                    models.ManyToManyField(
                        related_name="read_messages", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="notifications.messagethread",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["thread", "created_at"],
                        name="notificatio_thread__6299ef_idx",
                    ),
                    models.Index(
                        fields=["sender", "created_at"],
                        name="notificatio_sender__1c52f5_idx",
                    ),
                    models.Index(
                        fields=["thread", "is_deleted"],
                        name="notificatio_thread__d3434b_idx",
                    ),
                ],
            },
        ),
    ]
