# Generated by Django 4.2.26 on 2025-11-26 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="content_warning",
            field=models.TextField(
                blank=True, help_text="Warning message about content"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="flagged_reason",
            field=models.CharField(
                blank=True, help_text="Reason for flagging", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_content_safe",
            field=models.BooleanField(
                default=True, help_text="Whether content passed safety checks"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("flagged", "Flagged for Review"),
                    ("removed", "Removed by Moderator"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["moderation_status"], name="notificatio_moderat_0a029b_idx"
            ),
        ),
    ]
