# Generated by Django 4.2.26 on 2026-01-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "notifications",
            "0002_message_content_warning_message_flagged_reason_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="deleted_for_recipient",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="deleted_for_sender",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="is_urgent",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="sensitivity_level",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                db_index=True,
                default="low",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="messagethread",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="messagethread",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="messagethread",
            name="title",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="messagethread",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("job_interest", "Job Interest"),
                    ("job_application", "Job Application"),
                    ("shortlist", "Shortlisted for Job"),
                    ("profile_approval", "Profile Approval"),
                    ("profile_rejection", "Profile Rejection"),
                    ("profile_update_required", "Profile Update Required"),
                    ("message_received", "New Message"),
                    ("job_status_change", "Job Status Change"),
                    ("system_alert", "System Alert"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
