# Generated by Django 4.2.26 on 2025-11-25 12:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fayda_id",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{16}$", "Fayda ID must be 16 digits"
                            )
                        ],
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("place_of_birth", models.CharField(max_length=100)),
                ("region_of_origin", models.CharField(max_length=50)),
                ("current_location", models.CharField(max_length=100)),
                ("emergency_contact_name", models.CharField(max_length=100)),
                ("emergency_contact_phone", models.CharField(max_length=15)),
                ("languages", models.JSONField(default=list)),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Education"),
                            ("secondary", "Secondary Education"),
                            ("tertiary", "Tertiary Education"),
                            ("vocational", "Vocational Training"),
                            ("none", "No Formal Education"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "religion",
                    models.CharField(
                        choices=[
                            ("eth_orthodox", "Ethiopian Orthodox"),
                            ("islam", "Islam"),
                            ("protestant", "Protestant"),
                            ("catholic", "Catholic"),
                            ("traditional", "Traditional"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "working_time",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("live_in", "Live-in"),
                        ],
                        max_length=20,
                    ),
                ),
                ("skills", models.JSONField(default=list)),
                ("years_experience", models.IntegerField()),
                (
                    "profile_photo",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                (
                    "certifications",
                    models.FileField(
                        blank=True, null=True, upload_to="certifications/"
                    ),
                ),
                ("background_check_status", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
