# Generated by Django 4.2.26 on 2025-11-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workerprofile",
            name="languages",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
