# Generated by Django 4.2.26 on 2025-11-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workers", "0002_alter_workerprofile_languages_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workerprofile",
            name="age",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="background_check_status",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="current_location",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="education_level",
            field=models.CharField(
                choices=[
                    ("primary", "Primary Education"),
                    ("secondary", "Secondary Education"),
                    ("tertiary", "Tertiary Education"),
                    ("vocational", "Vocational Training"),
                    ("none", "No Formal Education"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="full_name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="is_approved",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="rating",
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=0.0, max_digits=3
            ),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="region_of_origin",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="religion",
            field=models.CharField(
                choices=[
                    ("eth_orthodox", "Ethiopian Orthodox"),
                    ("islam", "Islam"),
                    ("protestant", "Protestant"),
                    ("catholic", "Catholic"),
                    ("traditional", "Traditional"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="working_time",
            field=models.CharField(
                choices=[
                    ("full_time", "Full-time"),
                    ("part_time", "Part-time"),
                    ("live_in", "Live-in"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="years_experience",
            field=models.IntegerField(db_index=True),
        ),
    ]
