# Generated by Django 4.2.26 on 2025-11-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workers", "0003_alter_workerprofile_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workerprofile",
            name="fayda_id",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
