# Generated by Django 4.2.26 on 2026-01-18 12:06

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):
    dependencies = [
        ("workers", "0004_alter_workerprofile_fayda_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workerprofile",
            name="emergency_contact_name",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="emergency_contact_phone",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="fayda_id",
            field=encrypted_model_fields.fields.EncryptedCharField(unique=True),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="full_name",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="place_of_birth",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
