# Generated by Django 4.2.26 on 2026-01-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workers", "0005_alter_workerprofile_emergency_contact_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerprofile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
