# Generated by Django 4.2.26 on 2026-01-18 12:12

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("workers", "0006_workerprofile_deleted_at_workerprofile_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workerprofile",
            name="profile_photo",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to="profiles/"
            ),
        ),
    ]
