# Generated by Django 4.2.26 on 2025-11-26 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employers", "0002_alter_jobposting_language_requirements_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workers", "0004_alter_workerprofile_fayda_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("approve_worker", "Approve Worker Profile"),
                            ("reject_worker", "Reject Worker Profile"),
                            ("suspend_user", "Suspend User"),
                            ("flag_content", "Flag Content"),
                            ("moderate_job", "Moderate Job Posting"),
                            ("other", "Other Admin Action"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_job_posting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_actions",
                        to="employers.jobposting",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_targeted_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_worker_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_actions",
                        to="workers.workerprofile",
                    ),
                ),
            ],
        ),
    ]
