# Generated by Django 4.2.26 on 2026-01-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationlevel",
            name="sort_order",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
