# Generated by Django 4.2.26 on 2026-01-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_created_at_alter_user_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="data_processing_consent",
            field=models.BooleanField(default=False),
        ),
    ]
